version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - web
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    container_name: web
    build: ./services
    links:
      - db
    volumes:
     - /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web
volumes:
    postgres-data:
networks:
    web:
      driver: bridge