# Generated by Django 5.0.2 on 2024-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_is_deleted_bookingroom_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='currency',
            field=models.BooleanField(choices=[(True, 'BOB'), (False, 'USD')], default=True),
        ),
    ]
