# Generated by Django 5.0.2 on 2024-02-13 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_roomtype_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(choices=[(True, 'Free room'), (False, 'Occupied room')], default=True),
        ),
    ]
