# Generated by Django 5.0.2 on 2024-02-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bookingroom_booking_alter_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_data',
            new_name='payment_date',
        ),
        migrations.AlterField(
            model_name='paymentbookingroom',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.payment'),
        ),
    ]
